### ISSUE TITLE
Memory Corruption Error in Kernel _setup_linear

### ISSUE THREAD

**Issue by ethanbar11** [HazyResearch/state-spaces#56]
Hey,
I'm trying to use the forward_state function. From time to time, I get 
this error:
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1

Jumping out of:
File "/media/data2/ethan_baron/state-spaces-improv/src/models/sequence/ss/kernel.py", line 434, in _setup_linear
    R = torch.linalg.solve(R.to(Q_D), Q_D)  # (H r N)

Meaning,
from this lines (433-436) in the NPLR Kernel:
        try:
            R = torch.linalg.solve(R.to(Q_D), Q_D)  # (H r N)
        except torch._C._LinAlgError:
            R = torch.tensor(np.linalg.solve(R.to(Q_D).cpu(), Q_D.cpu())).to(Q_D)

I changed very little this lines for debugging, for:
try:
    R = torch.linalg.solve(R.to(Q_D), Q_D)  # (H r N)
except:
    x1 = R.to(Q_D).cpu()
    x2 = R.to(Q_D).cpu()
    R = torch.tensor(np.linalg.solve(x1, x2)).to(Q_D)

Full stack trace:

File "/media/data2/ethan_baron/state-spaces-improv/src/models/sequence/ss/kernel.py", line 434, in _setup_linear
    R = torch.linalg.solve(R.to(Q_D), Q_D)  # (H r N)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 724, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 812, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1237, in _run
    results = self._run_stage()
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1324, in _run_stage
    return self._run_train()
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1354, in _run_train
    self.fit_loop.run()
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 269, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 208, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 203, in advance
    result = self._run_optimization(
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 256, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 369, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1596, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/core/lightning.py", line 1625, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 278, in optimizer_step
    optimizer_output = super().optimizer_step(optimizer, opt_idx, closure, model, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 193, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 155, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/optim/adamw.py", line 100, in step
    loss = closure()
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 140, in _wrap_closure
    closure_result = closure()
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 148, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 134, in closure
    step_output = self._step_fn()
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 427, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *step_kwargs.values())
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1766, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 344, in training_step
    return self.model(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 963, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/overrides/base.py", line 82, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "/media/data2/ethan_baron/state-spaces-improv/train.py", line 302, in training_step
    loss = self._shared_step(batch, batch_idx, prefix="train")
  File "/media/data2/ethan_baron/state-spaces-improv/train.py", line 226, in _shared_step
    x, y, *w = self.forward(batch)
  File "/media/data2/ethan_baron/state-spaces-improv/train.py", line 186, in forward
    x, state = self.model(x, *w, state=self._state)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/data2/ethan_baron/state-spaces-improv/src/models/sequence/model.py", line 119, in forward
    outputs, state = layer(outputs, *args, state=state_to_use, **kwargs)  # TODO handle state
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/data2/ethan_baron/state-spaces-improv/src/models/sequence/block.py", line 91, in forward
    y, state = self.layer(y, *args, state=state, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/data2/ethan_baron/state-spaces-improv/src/models/sequence/ss/s4.py", line 238, in forward
    next_state = self.kernel.forward_state(u, state)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/data2/ethan_baron/state-spaces-improv/src/models/sequence/ss/kernel.py", line 1067, in forward_state
    self.kernel._setup_state()
  File "/media/data2/ethan_baron/state-spaces-improv/src/models/sequence/ss/kernel.py", line 497, in _setup_state
    self._setup_linear()
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/data2/ethan_baron/state-spaces-improv/src/models/sequence/ss/kernel.py", line 438, in _setup_linear
    x2 = Q_D.cpu()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/data2/ethan_baron/state-spaces-improv/train.py", line 561, in main
    train(config)
  File "/media/data2/ethan_baron/state-spaces-improv/train.py", line 506, in train
    print(trainer.fit(model))#,ckpt_path=r"/media/media1/ethan_baron/state-spaces-improvements/outputs/2022-06-24/21-59-15/checkpoints/last.ckpt"))
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 771, in fit
    self._call_and_handle_interrupt(
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _call_and_handle_interrupt
    self.strategy.reconciliate_processes(traceback.format_exc())
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 446, in reconciliate_processes
    raise DeadlockDetectedException(f"DeadLock detected from rank: {self.global_rank} \n {trace}")
pytorch_lightning.utilities.exceptions.DeadlockDetectedException: DeadLock detected from rank: 1
 Traceback (most recent call last):
  File "/media/data2/ethan_baron/state-spaces-improv/src/models/sequence/ss/kernel.py", line 434, in _setup_linear
    R = torch.linalg.solve(R.to(Q_D), Q_D)  # (H r N)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 724, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 812, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1237, in _run
    results = self._run_stage()
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1324, in _run_stage
    return self._run_train()
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1354, in _run_train
    self.fit_loop.run()
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 269, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 208, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 203, in advance
    result = self._run_optimization(
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 256, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 369, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1596, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/core/lightning.py", line 1625, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 278, in optimizer_step
    optimizer_output = super().optimizer_step(optimizer, opt_idx, closure, model, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 193, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 155, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/optim/adamw.py", line 100, in step
    loss = closure()
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 140, in _wrap_closure
    closure_result = closure()
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 148, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 134, in closure
    step_output = self._step_fn()
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 427, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *step_kwargs.values())
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1766, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 344, in training_step
    return self.model(*args, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 963, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/pytorch_lightning/overrides/base.py", line 82, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "/media/data2/ethan_baron/state-spaces-improv/train.py", line 302, in training_step
    loss = self._shared_step(batch, batch_idx, prefix="train")
  File "/media/data2/ethan_baron/state-spaces-improv/train.py", line 226, in _shared_step
    x, y, *w = self.forward(batch)
  File "/media/data2/ethan_baron/state-spaces-improv/train.py", line 186, in forward
    x, state = self.model(x, *w, state=self._state)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/data2/ethan_baron/state-spaces-improv/src/models/sequence/model.py", line 119, in forward
    outputs, state = layer(outputs, *args, state=state_to_use, **kwargs)  # TODO handle state
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/data2/ethan_baron/state-spaces-improv/src/models/sequence/block.py", line 91, in forward
    y, state = self.layer(y, *args, state=state, **kwargs)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/data2/ethan_baron/state-spaces-improv/src/models/sequence/ss/s4.py", line 238, in forward
    next_state = self.kernel.forward_state(u, state)
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/data2/ethan_baron/state-spaces-improv/src/models/sequence/ss/kernel.py", line 1067, in forward_state
    self.kernel._setup_state()
  File "/media/data2/ethan_baron/state-spaces-improv/src/models/sequence/ss/kernel.py", line 497, in _setup_state
    self._setup_linear()
  File "/home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/data2/ethan_baron/state-spaces-improv/src/models/sequence/ss/kernel.py", line 438, in _setup_linear
    x2 = Q_D.cpu()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[W CUDAGuardImpl.h:113] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1646756402876/work/c10/cuda/CUDACachingAllocator.cpp:1230 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x4d (0x7fdd849ac1bd in /home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1f037 (0x7fddb6ff9037 in /home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x23a (0x7fddb6ffd3ea in /home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x2ecdd8 (0x7fde079f2dd8 in /home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #4: c10::TensorImpl::release_resources() + 0x175 (0x7fdd84992fb5 in /home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #5: std::vector<c10d::Reducer::Bucket, std::allocator<c10d::Reducer::Bucket> >::~vector() + 0x2e9 (0x7fddba5b3039 in /home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::Reducer::~Reducer() + 0x205 (0x7fddba5a5775 in /home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #7: std::_Sp_counted_ptr<c10d::Reducer*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() + 0x12 (0x7fde07ee7062 in /home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #8: std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() + 0x46 (0x7fde078e1706 in /home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x7e49cf (0x7fde07eea9cf in /home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x1e3536 (0x7fde078e9536 in /home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0x1e4afe (0x7fde078eaafe in /home/ethan_baron/miniconda3/envs/s4ker/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #12: <unknown function> + 0x129d5b (0x56004b0d2d5b in /home/ethan_baron/miniconda3/envs/s4ker/bin/python)
frame #13: <unknown function> + 0x194655 (0x56004b13d655 in /home/ethan_baron/miniconda3/envs/s4ker/bin/python)
frame #14: <unknown function> + 0x129d5b (0x56004b0d2d5b in /home/ethan_baron/miniconda3/envs/s4ker/bin/python)
frame #15: <unknown function> + 0x12a950 (0x56004b0d3950 in /home/ethan_baron/miniconda3/envs/s4ker/bin/python)
frame #16: <unknown function> + 0x13a9dd (0x56004b0e39dd in /home/ethan_baron/miniconda3/envs/s4ker/bin/python)
frame #17: _PyGC_CollectNoFail + 0x35 (0x56004b203705 in /home/ethan_baron/miniconda3/envs/s4ker/bin/python)
frame #18: <unknown function> + 0x2744ba (0x56004b21d4ba in /home/ethan_baron/miniconda3/envs/s4ker/bin/python)
frame #19: Py_FinalizeEx + 0x186 (0x56004b21d7a6 in /home/ethan_baron/miniconda3/envs/s4ker/bin/python)
frame #20: Py_RunMain + 0x10c (0x56004b222e8c in /home/ethan_baron/miniconda3/envs/s4ker/bin/python)
frame #21: Py_BytesMain + 0x39 (0x56004b223309 in /home/ethan_baron/miniconda3/envs/s4ker/bin/python)
frame #22: __libc_start_main + 0xf3 (0x7fde637f40b3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #23: <unknown function> + 0x2010a0 (0x56004b1aa0a0 in /home/ethan_baron/miniconda3/envs/s4ker/bin/python)

**Comment by albertfgu** [comment]
I looked into this recently and also found the same issue, which wasn't present before. I wasn't able to figure out why. It's weird that it happens randomly.

Regardless, the implementation of "state forwarding" ([README](https://github.com/HazyResearch/state-spaces/tree/main/src/models/s4#state-forwarding)) is currently unoptimized for S4 so it is not recommended to use this. If you want this functionality, it should work with S4D. Feel free to file another issue if something comes up.

Finally, could you please edit the original issue here to be shorter, and in particular remove at least the last part of the stack trace. It might also help to put the whole thing in a code block. The last few lines are all parsed in a way that references other Issues which is confusing.

**Comment by ethanbar11** [comment]
Yeah, I tried to look into it for a couple of days and didn't understand what happened.
I'm using now the S4D forward_state version and until now it works quite well. 
Edited the issue, hopefully to be more readable.
Thanks!
